// Scaffolder - Generate project structures from templates
import fs from 'fs/promises';
import path from 'path';
import { execSync } from 'child_process';

const TEMPLATES = {
  nextjs: {
    name: 'Next.js + TypeScript + Tailwind',
    stack: ['Node.js', 'React', 'TypeScript'],
    files: {
      'package.json': (name) => JSON.stringify({
        name,
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint'
        },
        dependencies: {
          next: '^14.0.0',
          react: '^18.0.0',
          'react-dom': '^18.0.0'
        },
        devDependencies: {
          '@types/node': '^20.0.0',
          '@types/react': '^18.0.0',
          autoprefixer: '^10.0.0',
          eslint: '^8.0.0',
          'eslint-config-next': '^14.0.0',
          postcss: '^8.0.0',
          tailwindcss: '^3.0.0',
          typescript: '^5.0.0'
        }
      }, null, 2),
      'tsconfig.json': () => JSON.stringify({
        compilerOptions: {
          target: 'es5',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          forceConsistentCasingInFileNames: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          paths: { '@/*': ['./src/*'] }
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
        exclude: ['node_modules']
      }, null, 2),
      'tailwind.config.js': () => `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: { extend: {} },
  plugins: [],
}`,
      'postcss.config.js': () => `module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } }`,
      'next.config.js': () => `/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true }
module.exports = nextConfig`,
      'README.md': (name) => `# ${name}\n\nNext.js project scaffolded by Warp Platform.\n\n## Getting Started\n\n\`\`\`bash\nnpm run dev\n\`\`\`\n\nOpen [http://localhost:3000](http://localhost:3000)`,
      '.gitignore': () => `node_modules\n.next\nout\ndist\n.env*.local`,
      'src/app/page.tsx': () => `export default function Home() {
  return <main className="min-h-screen p-24"><h1 className="text-4xl font-bold">Welcome to Next.js</h1></main>
}`,
      'src/app/layout.tsx': (name) => `export const metadata = { title: '${name}', description: 'Generated by Warp' }
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="en"><body>{children}</body></html>
}`,
      'src/app/globals.css': () => `@tailwind base;\n@tailwind components;\n@tailwind utilities;`
    },
    postCreate: async (projectPath) => {
      execSync('npm install', { cwd: projectPath, stdio: 'inherit' });
    }
  },

  express: {
    name: 'Express.js API',
    stack: ['Node.js', 'JavaScript'],
    files: {
      'package.json': (name) => JSON.stringify({
        name,
        version: '1.0.0',
        type: 'module',
        scripts: {
          start: 'node src/index.js',
          dev: 'node --watch src/index.js',
          test: 'echo "Error: no test specified" && exit 1'
        },
        dependencies: {
          express: '^4.18.0',
          cors: '^2.8.5',
          dotenv: '^16.0.0'
        },
        devDependencies: {
          nodemon: '^3.0.0'
        }
      }, null, 2),
      'README.md': (name) => `# ${name}\n\nExpress.js API scaffolded by Warp Platform.\n\n## Getting Started\n\n\`\`\`bash\nnpm run dev\n\`\`\``,
      '.gitignore': () => `node_modules\n.env\ndist`,
      '.env.example': () => `PORT=3000\nNODE_ENV=development`,
      'src/index.js': () => `import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

app.get('/', (req, res) => {
  res.json({ message: 'Express API - Powered by Warp' });
});

app.get('/api/health', (req, res) => {
  res.json({ status: 'healthy', timestamp: new Date().toISOString() });
});

app.listen(PORT, () => {
  console.log(\`Server running on http://localhost:\${PORT}\`);
});`,
      'src/routes/index.js': () => `import express from 'express';
const router = express.Router();

router.get('/', (req, res) => {
  res.json({ message: 'API Routes' });
});

export default router;`
    },
    postCreate: async (projectPath) => {
      execSync('npm install', { cwd: projectPath, stdio: 'inherit' });
    }
  },

  python: {
    name: 'Python FastAPI',
    stack: ['Python'],
    files: {
      'requirements.txt': () => `fastapi==0.104.0
uvicorn[standard]==0.24.0
pydantic==2.5.0
python-dotenv==1.0.0`,
      'README.md': (name) => `# ${name}\n\nFastAPI project scaffolded by Warp Platform.\n\n## Getting Started\n\n\`\`\`bash\npython -m venv venv\nsource venv/bin/activate  # Windows: venv\\Scripts\\activate\npip install -r requirements.txt\nuvicorn main:app --reload\n\`\`\``,
      '.gitignore': () => `__pycache__\n*.py[cod]\n*$py.class\nvenv\n.env\ndist\nbuild`,
      '.env.example': () => `DEBUG=True\nHOST=0.0.0.0\nPORT=8000`,
      'main.py': () => `from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv
import os

load_dotenv()

app = FastAPI(title="FastAPI - Powered by Warp")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    return {"message": "FastAPI - Powered by Warp"}

@app.get("/api/health")
async def health():
    return {"status": "healthy"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)`,
      'api/__init__.py': () => '',
      'api/routes.py': () => `from fastapi import APIRouter

router = APIRouter()

@router.get("/")
async def api_root():
    return {"message": "API Routes"}`
    },
    postCreate: async (projectPath) => {
      // Python setup handled separately by user
    }
  },

  blank: {
    name: 'Blank Project',
    stack: ['JavaScript'],
    files: {
      'README.md': (name) => `# ${name}\n\nBlank project scaffolded by Warp Platform.\n\nAdd your code here!`,
      '.gitignore': () => `node_modules\ndist\n.env`
    },
    postCreate: async () => {}
  }
};

const WARP_CONFIG_TEMPLATES = {
  nodejs: {
    'agents.yml': `agents:
  - id: planner
    name: Project Planner
    model: o3-mini
    role: architect
    expertise: [system-design, requirements, planning]
    instructions: |
      Analyze requirements, break down complex tasks, create implementation plans.
      Focus on scalability, maintainability, and best practices.

  - id: coder
    name: Senior Developer
    model: claude-sonnet-4
    role: implementer
    expertise: [javascript, typescript, react, node, testing]
    instructions: |
      Write clean, efficient code following best practices.
      Implement features with proper error handling and tests.

  - id: reviewer
    name: Code Reviewer
    model: claude-sonnet-4
    role: quality
    expertise: [code-review, refactoring, optimization]
    instructions: |
      Review code for bugs, performance issues, security vulnerabilities.
      Suggest improvements and ensure code quality standards.`,

    'skills.yml': `skills:
  - id: test-runner
    name: Run Tests
    command: npm test
    triggers: [after-code-change, before-commit]

  - id: linter
    name: Lint Code
    command: npm run lint
    triggers: [before-commit]

  - id: build
    name: Build Project
    command: npm run build
    triggers: [before-deploy]`
  },

  python: {
    'agents.yml': `agents:
  - id: planner
    name: Python Architect
    model: o3-mini
    role: architect
    expertise: [python, system-design, api-design]
    instructions: |
      Design Python applications with proper structure, async patterns, type hints.
      Focus on performance and Pythonic code.

  - id: coder
    name: Python Developer
    model: claude-sonnet-4
    role: implementer
    expertise: [python, fastapi, django, pytest]
    instructions: |
      Write clean Python code with type hints, docstrings, and tests.
      Follow PEP 8 and Python best practices.

  - id: reviewer
    name: Python Reviewer
    model: claude-sonnet-4
    role: quality
    expertise: [code-review, python, testing]
    instructions: |
      Review Python code for correctness, performance, type safety.
      Ensure proper error handling and documentation.`,

    'skills.yml': `skills:
  - id: test-runner
    name: Run Tests
    command: pytest
    triggers: [after-code-change]

  - id: linter
    name: Lint Code
    command: ruff check .
    triggers: [before-commit]`
  }
};

export async function scaffoldProject(projectData) {
  const { name, template, basePath } = projectData;
  const projectPath = path.join(basePath, name);

  const templateConfig = TEMPLATES[template];
  if (!templateConfig) throw new Error(`Template ${template} not found`);

  // Create project directory
  await fs.mkdir(projectPath, { recursive: true });

  // Initialize git
  try {
    execSync('git init', { cwd: projectPath, stdio: 'ignore' });
  } catch (e) {
    console.warn('Git init failed:', e.message);
  }

  // Create files from template
  for (const [filePath, contentFn] of Object.entries(templateConfig.files)) {
    const fullPath = path.join(projectPath, filePath);
    const dir = path.dirname(fullPath);
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(fullPath, contentFn(name));
  }

  // Create .warp/ config
  const warpPath = path.join(projectPath, '.warp');
  await fs.mkdir(warpPath, { recursive: true });

  const stackType = templateConfig.stack.includes('Python') ? 'python' : 'nodejs';
  const warpConfig = WARP_CONFIG_TEMPLATES[stackType];

  for (const [file, content] of Object.entries(warpConfig)) {
    await fs.writeFile(path.join(warpPath, file), content);
  }

  // Run post-create hook (npm install, etc)
  if (templateConfig.postCreate) {
    await templateConfig.postCreate(projectPath);
  }

  return {
    path: projectPath,
    stack: templateConfig.stack,
    template: templateConfig.name
  };
}

export function getAvailableTemplates() {
  return Object.entries(TEMPLATES).map(([id, config]) => ({
    id,
    name: config.name,
    stack: config.stack
  }));
}