name: Feature request
about: Suggest an idea
labels: enhancement
body:
  - type: textarea
    id: goal
    attributes:
      label: Objective
      description: One-sentence outcome
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What to change; what NOT to change
  - type: textarea
    id: validation
    attributes:
      label: Validation
      description: Lint/tests/dry-run
  - type: textarea
    id: notes
    attributes:
      label: Notes