# Validate Markdown and YAML with markdownlint and yamllint
name: Docs Lint
on:
  pull_request:
    branches: [ main ]
jobs:
  markdown_yaml_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install markdownlint-cli2
        run: npm i -g markdownlint-cli2
      - name: Run markdownlint
        run: markdownlint-cli2 "**/*.md" "!node_modules"
      - name: Install yamllint
        run: |
          sudo apt-get update && sudo apt-get install -y yamllint
      - name: Run yamllint
        run: yamllint -d '{extends: default, rules: {line-length: disable}}' .
