# Lint bash with shellcheck and PowerShell with PSScriptAnalyzer
name: Scripts Lint
on:
  pull_request:
    branches: [ main ]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: |
          shopt -s globstar || true
          shellcheck -x **/*.sh || true
  psscriptanalyzer:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module PSScriptAnalyzer -Force -Scope CurrentUser
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $files = Get-ChildItem -Recurse -Filter *.ps1 | Select-Object -ExpandProperty FullName
          if ($files.Count -gt 0) { Invoke-ScriptAnalyzer -Path $files -Recurse -Severity Warning } else { Write-Host "No ps1 files" }
