name: Warp Workflow Validator
on:
  pull_request:
    branches: [ main ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML
        run: |
          set -e
          sudo apt-get update && sudo apt-get install -y yamllint
          yamllint -d '{extends: default, rules: {line-length: disable}}' 05_WORKFLOWS
